### ISSUE TITLE
File_Skimmer.OpenFile doesn't check to see if the file exists before opening

### ISSUE THREAD

**Issue by pfgithub** [ShiftOS/ShiftOS#1]

**Comment by AlphaBeta0110** [comment]
I believe the file wouldn't even show up if it didn't exist. I'll look at it tomorrow.

**Comment by pfgithub** [comment]
The file won't show up, but this is part of the file skimmer API
If someone were to try to open a nonexistent file in another program, there will be an error depending on the file typr

**Comment by TheUltimateHacker** [comment]
Right, got the issue fixed.
