### ISSUE TITLE
Mod API

### ISSUE THREAD

**Issue by rezedus** [ShiftOS/ShiftOS#19]
We haven't decided on how will the Mod API look like, thereby I am making this issue for the discussion.

**Comment by AlphaBeta0110** [comment]
I propose basing it off the API which would be existing when the rewrite is complete. A developer would just add a reference to the ShiftOS exe and the classes we want them to see could be inherited and used. The mods would be written in C#, Visual Basic or whatever language can run on top of the .NET runtime. If this approach is chosen, I'll take core of the mod engine, this'd use System.Reflection classes and I've got quite some experience with them.

**Comment by jamierocks** [comment]
Perhaps aswell as a .net API, have a lua, python, javascript, etc library too.

**Comment by jamierocks** [comment]
@pfgithub perhaps link to commit, containing the API code?

**Comment by pfgithub** [comment]
http://shiftos.net/topic1557.html
