### ISSUE TITLE
Make a ShiftOS github organization and move the repo to it

### ISSUE THREAD

**Issue by rezedus** [ShiftOS/ShiftOS#4]
A GitHub organization is like a BitBucket team.

V0rTeX would need to change his name in Settings, then somebody would create the organization (called ShiftOS) and move the ownership of this repo to that org.

**Comment by jamierocks** [comment]
Or V0rtex, could create an account for himself, and change the ShiftOS account to an organization?

**Comment by V0rTeXbg** [comment]
Done
